services:
  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo
    restart: always #Si el contendior cau o falla per culpa de MongoDB, docker intenta inizialitzar-lo un altre cop per a que el servei segueixi funcionant. 
                    # O també si el OS es reinicia docker inicia automaticament els contenidors al arrencar el OS
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ecommerce-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  mongo_data:
